### ISSUE TITLE
Insert data from other tables

### ISSUE THREAD

**Issue by d3x7r0** [irenical/drowsy#11]
It looks like there's no easy way to insert data into a table by selecting it from a different one:

```sql
INSERT INTO phone_book2 ( [name], [phoneNumber] )
SELECT [name], [phoneNumber]
FROM   phone_book
WHERE  name IN ('John Doe', 'Peter Doe')
```
https://en.wikipedia.org/wiki/Insert_(SQL)#Copying_rows_from_other_tables

**Comment by tiagosimao** [comment]
Try to use the .subquery() method. It wraps parentheses around the sub-select but seems to work ok (in PostgreSQL).
If this behavior turns out to be undesirable, a new method (select?) in the InsertBuilder should easily fix it.

**Comment by d3x7r0** [comment]
Yes, it looks like that might work. It adds some extra parenthesis but those don't seem to prevent the query from working. I think this can be closed and left for future reference.
